export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_COMPLETE = "SIGNIN_COMPLETE";
export const GET_USER_INFORMATION = "GET_USER_INFORMATION";
export const UPDATE_AUTHENTICATE = "UPDATE_AUTHENTICATE";
export const SIGNOUT_START = "SIGNOUT_START";
export const SIGNOUT_COMPLETE = "SIGNOUT_COMPLETE";
